django_primer/urls.py
from django.contrib import admin
from django.urls import path

from .views import ReportView, ScoreListView, SubjectListView, \
StudentListView, IndexView, ScoreCreateView, SubjectCreateView, StudentCreateView, \
StudentUpdateView, StudentDeleteView, SubjectDeleteView, SubjectUpdateView, ScoreDeleteView, \
ScoreUpdateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),

    path('score/list/', ScoreListView.  as_view(), name='score_list'),
    path('score/form/', ScoreCreateView.as_view(), name='score_create'),
    path('score/<int:pk>/update/', ScoreUpdateView.as_view(), name='score_update'),
    path('score/<int:pk>/delete/', ScoreDeleteView.as_view(), name='score_delete'),

    path('student/list/', StudentListView.as_view(), name='student_list'),
    path('student/form/', StudentCreateView.as_view(), name='student_create'),
    path('student/<int:pk>/update/', StudentUpdateView.as_view(), name='student_update'),
    path('student/<int:pk>/delete/', StudentDeleteView.as_view(), name='student_delete'),

    path('subject/list/', SubjectListView.as_view(), name='subject_list'),
    path('subject/form/', SubjectCreateView.as_view(), name='subject_create'),
    path('subject/<int:pk>/update/', SubjectUpdateView.as_view(), name='subject_update'),
    path('subject/<int:pk>/delete/', SubjectDeleteView.as_view(), name='subject_delete'),

    path('report/', ReportView.as_view(), name='report')
]

django_primer/models/score.py
from django.db import models
from .student import Student
from .subject import Subject

class Score(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    value = models.FloatField(blank=False, null=False)

    def __str__(self):
        return f'{self.student.fio}: {self.subject} -> {self.value:.2f}'

    def __repr__(self):
        return f'Student(student="{self.student}", subject="{self.subject}", value="{self.value}")'

django_primer/models/student.py
from django.db import models

class Student(models.Model):
    last_name = models.CharField(max_length=200, null=False)
    first_name = models.CharField(max_length=200, null=False)
    patronymic = models.CharField(max_length=200, null=True)
    birth_date = models.DateField()
    email = models.EmailField(null=False)

    @property
    def name(self):
        return f'{self.last_name} {self.first_name} {self.patronymic}' if self.patronymic else f'{self.last_name} {self.first_name}'

    def __str__(self):
        return f'{self.fio} ({self.email})'

    def __repr__(self):
        return f'Student(last_name="{self.last_name}", first_name="{self.first_name}", patronymic="{self.patronymic}", email="{self.email}")'

django_primer/models/subject.py
from django.db import models

class Subject(models.Model):
    name = models.CharField(max_length=20, null=False)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f'Subject(name="{self.name}")'

django_primer/views/index_view.py
from django.db.models import Avg
from django.views.generic import TemplateView
from ..models import Student, Subject, Score

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subjects = Subject.objects.all()
        students = Student.objects.all()

        student_statistics = []

        for student in students:
            scores = []
            for subject in subjects:
                score = Score.objects.filter(student=student, subject=subject) \
                .aggregate(average_score=Avg('value'))['average_score']
                scores.append(score if score else '-')
            student_statistics.append({
                'student': student,
                'scores': scores
            })

        context['subjects'] = subjects
        context['student_statistics'] = student_statistics
        return context

django_primer/views/report_views.py
from django.db.models import Avg, F, Value, Case, When
from django.db.models.functions import Concat
from django.views.generic import TemplateView
from ..models import Score

class ReportView(TemplateView):
    template_name = 'report.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Средний балл каждого студента
        student_averages = list(
        Score.objects.annotate(
            student_name=Case(
                When(
                    student__patronymic__isnull=True,
                    then=Concat(F('student__last_name'), Value(' '), F('student__first_name'))
                    ),            
                default=Concat(F('student__last_name'), Value(' '), F('student__first_name'), Value(' '), F('student__patronymic'))
            )
        )
        .values('student_name') 
                .annotate(average_score=Avg('value'))
                .order_by('-average_score')
            )
        
        # Средний балл по предметам
        subject_averages = list(
            Score.objects.values('subject__name')
            .annotate(average_score=Avg('value'))
            .order_by('-average_score')
        )
        
        # Распределение лучшего и худшего студента на основе среднего балла
        if student_averages:
            context['student_averages'] = student_averages
            context['best_student'] = student_averages[0]
            context['worst_student'] = student_averages[-1]
        else:
            context['student_averages'] = []
            context['best_student'] = None
            context['worst_student'] = None
            
        context['subject_averages'] = subject_averages

        return context

django_primer/views/score_views.py
from django.forms import ModelForm
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from ..models import Score, Student, Subject

class ScoreListView(ListView):
    model = Score
    template_name = 'score_list.html'

class ScoreCreateView(CreateView):
    model = Score
    template_name = 'score_form.html'
    fields = ['student', 'subject', 'value']
    success_url = reverse_lazy('score_list')

class ScoreUpdateView(UpdateView):
    model = Score
    template_name = 'score_form.html'
    fields = ['student', 'subject', 'value']
    success_url = reverse_lazy('score_list')

class ScoreDeleteView(DeleteView):
    model = Score
    template_name = 'score_confirm_delete.html'
    success_url = reverse_lazy('score_list')

django_primer/views/student_views.py
from django.urls import reverse_lazy
from django import forms
from django.views.generic import ListView, CreateView, UpdateView, DeleteView,TemplateView
from ..models import Student, Subject, Score

class StudentListView(ListView):
    model = Student
    template_name = 'student_list.html'

class StudentCreateView(CreateView):
    model = Student
    template_name = 'student_form.html'
    fields = ['last_name', 'first_name','patronymic','birth_date','email']
    success_url = reverse_lazy('student_list')

class StudentUpdateView(UpdateView):
    model = Student
    template_name = 'student_form.html'
    fields = ['last_name', 'first_name','patronymic','birth_date','email']
    widgets = {
    'birth_date': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
}
    success_url = reverse_lazy('student_list')

class StudentDeleteView(DeleteView):
    model = Student
    template_name = 'student_confirm_delete.html'
    success_url = reverse_lazy('student_list')

django_primer/views/subject_views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from ..models import Subject

class SubjectListView(ListView):
    model = Subject
    template_name = 'subject_list.html'

class SubjectCreateView(CreateView):
    model = Subject
    template_name = 'subject_form.html'
    fields = ['name']
    success_url = reverse_lazy('subject_list')

class SubjectUpdateView(UpdateView):
    model = Subject
    template_name = 'subject_form.html'
    fields = ['name']
    success_url = reverse_lazy('subject_list')

class SubjectDeleteView(DeleteView):
    model = Subject
    template_name = 'subject_confirm_delete.html'
    success_url = reverse_lazy('subject_list')

django_primer/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Система учета успеваемости студентов</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .container {
            width: 80%;
            margin: auto;
        }

        .footer {
            margin-top: 20px;
            padding: 20px 0;
            text-align: center;
            background-color: #f7f7f7;
            border-top: 1px solid #e7e7e7;
        }

        .btn-custom {
            background-color: #5cb85c;
            color: white;
        }

        .btn-custom:hover {
            background-color: #449d44;
        }

        .header {
            background: linear-gradient(90deg, #034993, #007bff 72.23%);
            padding-bottom: 10px;

        }

        .header h1 {
            font-family: Montserrat;
            padding: 20px 0;
            color: #fff;
            font-weight: 600;
            font-size: 36px;
            line-height: 51px;
            color: #fff;
        }

        .header a {
            text-decoration: none;
        }

        .form-container {
            background-color: #fff;
            padding: 15px;
            border-radius: 8px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }

        .table-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        .content {
            padding: 20px;
            min-height: calc(100vh - 200px);

        }

        .custom-link {
            color: black;
            text-decoration: none;
            margin-bottom: 30px;
            display: inline-block;
        }

        .custom-link:hover {
            text-decoration: none;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="container">
            <a href="{% url 'index' %}">
                <h1>Система учета успеваемости студентов</h1>
            </a>
        </div>
    </div>
    <div class="content">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div class="footer">
        <div class="container">
            &copy; 2024 IT-академия ТУСУР. Сидоров Владислав Владимирович. Все права защищены.
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

django_primer/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row mt-0">
    <div class="col-md-3">
        <div class="list-group">
            <h5 class="list-group-item active text-center mb-0">Управление</h5>
            <a href="{% url 'student_list' %}" class="list-group-item list-group-item-action">Студенты</a>
            <a href="{% url 'subject_list' %}" class="list-group-item list-group-item-action">Предметы</a>
            <a href="{% url 'score_list' %}" class="list-group-item list-group-item-action">Оценки</a>
            <a href="{% url 'report' %}" class="list-group-item list-group-item-action">Показать отчёт</a>
        </div>
    </div>

    <div class="col-md-9">
        <div class="table-container">
            <h2 class="text-center">Успеваемость студентов</h2>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>ФИО студента</th>
                        {% for subject in subjects %}
                        <th>{{ subject.name }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for statistics in student_statistics %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ statistics.student.name }}</td>
                        {% for score in statistics.scores %}
                        <td>{{ score }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

django_primer/templates/report.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container-no-padding">
    <div class="table-container">
        <a href="{% url 'index' %}" class="mb-3 custom-link">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
                viewBox="0 0 20 20">
                <path fill-rule="evenodd"
                    d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
            </svg>
            Назад
        </a>
        <h2>Отчет об успеваемости</h2>
        <div class="report-section ">
            <h3 class="text-center">Средний балл по каждому студенту</h3>
            <table class="table table-bordered table-hover mt-4">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>ФИО студента</th>
                        <th>Средний балл</th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in student_averages %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ student.student_name }}</td>
                        <td>{{ student.average_score|floatformat:2 }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="report-section mt-4">
            <h3 class="text-center">Средние баллы по предметам</h3>
            <table class="table table-bordered  mt-4 table-hover">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>Название предмета</th>
                        <th>Средний балл</th>
                    </tr>
                </thead>
                <tbody>
                    {% for subject in subject_averages %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ subject.subject__name }}</td>
                        <td>{{ subject.average_score|floatformat:2 }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="report-section mt-4 mb-5">
            <h3 class="text-center">Лучший и xудший студенты</h3>
            <div class="row mt-4">
                <div class="col-md-6">
                    <p><strong>Лучший студент:</strong></p>
                    <p>{{ best_student.student_name }} со средним
                        баллом {{ best_student.average_score|floatformat:2 }}</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Худший студент:</strong></p>
                    <p> {{ worst_student.student_name }} со средним
                        баллом {{ worst_student.average_score|floatformat:2 }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_primer/templates/score_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container-no-padding">
    <div class="table-container">
        <h2>Удаление оценки</h2>
        <p>Вы уверены, что хотите удалить эту запись?</p>

        <div class="alert alert-warning" role="alert">
            <strong>Предупреждение:</strong> Это действие не может быть отменено.
        </div>

        <div class="details">
            <p><strong>Студент:</strong> {{ object.student.name }}</p>
            <p><strong>Предмет:</strong> {{ object.subject.name }}</p>
            <p><strong>Оценка:</strong> {{ object.value }}</p>
        </div>

        <form action="" method="post">
            {% csrf_token %}
            <a href="{% url 'score_list' %}" class="btn btn-secondary">Отмена</a>
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
</div>
{% endblock %}

django_primer/templates/score_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="form-container">
    <h2>{% if object %}Изменить{% else %}Добавить{% endif %} Оценку</h2>
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_student">Студент:</label>
            <select id="id_student" name="student" class="form-control">
                {% for student in form.fields.student.queryset %}
                <option value="{{ student.id }}">{{student.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_subject">Предмет:</label>
            <select id="id_subject" name="subject" class="form-control">
                {% for subject in form.fields.subject.queryset %}
                <option value="{{ subject.id }}">{{subject.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_value">Оценка:</label>
            <input type="number" class="form-control" id="id_value" name="value" min="1" max="5"
                value="{{ form.value.value|default_if_none:'' }}" required>
        </div>
        <button type="submit" class="btn btn-custom">Сохранить</button>
        <button type="button" onclick="history.back()" class="btn btn-secondary">Отмена</button>
    </form>
</div>
{% endblock %}

django_primer/templates/score_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="table-container">
    <a href="{% url 'index' %}" class="mb-3 custom-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
            viewBox="0 0 20 20">
            <path fill-rule="evenodd"
                d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
        </svg>
        Назад
    </a>
    <h2>Оценки</h2>
    <a href="{% url 'score_create' %}" class="btn btn-success mb-3">Поставить оценку</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Студент</th>
                <th>Предмет</th>
                <th>Оценка</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for score in object_list %}
            <tr>
                <td>{{ score.student.name }}</td>
                <td>{{ score.subject.name }}</td>
                <td>{{ score.value }}</td>
                <td class="text-right">
                    <a href="{% url 'score_update' score.id %}" class="btn btn-primary">Редактировать</a>
                    <a href="{% url 'score_delete' score.id %}" class="btn btn-danger">Удалить</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

django_primer/templates/student_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="form-container">
    <h2>Вы уверены, что хотите удалить студента "{{ object.name }}"?</h2>
    <form method="post" class="form mt-4">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Удалить">
        <a href="{% url 'student_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

django_primer/templates/student_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="form-container">
    <h2>{% if object %}Изменить{% else %}Создать{% endif %} студента</h2>
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_last_name">Фамилия:</label>
            <input type="text" class="form-control" id="id_last_name" name="last_name"
                value="{{ form.last_name.value|default_if_none:'' }}" required>
        </div>
        <div class="form-group">
            <label for="id_first_name">Имя:</label>
            <input type="text" class="form-control" id="id_first_name" name="first_name"
                value="{{ form.first_name.value|default_if_none:'' }}" required>
        </div>
        <div class="form-group">
            <label for="id_patronymic">Отчество:</label>
            <input type="text" class="form-control" id="id_patronymic" name="patronymic"
                value="{{ form.patronymic.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="id_birth_date">Дата рождения:</label>
            <input type="date" class="form-control" id="id_birth_date" name="birth_date"
                value="{{ form.birth_date.value|date:'Y-m-d'|default_if_none:'' }}" required>
        </div>
        <div class="form-group">
            <label for="id_email">Email:</label>
            <input type="email" class="form-control" id="id_email" name="email"
                value="{{ form.email.value|default_if_none:'' }}" required>
        </div>
        <button type="submit" class="btn btn-custom">Сохранить</button>
        <button type="button" onclick="history.back()" class="btn btn-secondary">Отмена</button>
    </form>
</div>
{% endblock %}

django_primer/templates/student_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="table-container">
    <a href="{% url 'index' %}" class="mb-3 custom-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
            viewBox="0 0 20 20">
            <path fill-rule="evenodd"
                d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
        </svg>
        Назад
    </a>
    <h2>Студенты</h2>
    <a href="{% url 'student_create' %}" class="btn btn-success mb-3">Добавить</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Имя</th>
                <th>Дата Рождения</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for student in object_list %}
            <tr>
                <td>{{ student.name }}</td>
                <td>{{ student.birth_date|date:"Y-m-d" }}</td>
                <td class="text-right">
                    <a href="{% url 'student_update' student.id %}" class="btn btn-primary">Редактировать</a>
                    <a href="{% url 'student_delete' student.id %}" class="btn btn-danger">Удалить</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

django_primer/templates/subject_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="form-container">
    <h2>Вы уверены, что хотите удалить тему "{{ object.name }}"?</h2>
    <form method="post" class="form mt-4">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Удалить">
        <a href="{% url 'subject_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

django_primer/templates/subject_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="form-container">
    <h2>{% if object %}Измнить{% else %}Создать{% endif %} предмет</h2>
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Название:</label>
            <input type="text" class="form-control" id="id_name" name="name" value="{{ form.name.value|default_if_none:'' }}" required>
        </div>
        <button type="submit" class="btn btn-custom">Сохранить</button>
        <button onclick="history.back()" class="btn btn-secondary">Отмена</button>
    </form>
</div>
{% endblock %}

django_primer/templates/subject_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="table-container">
    <a href="{% url 'index' %}" class="mb-3 custom-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
            viewBox="0 0 20 20">
            <path fill-rule="evenodd"
                d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
        </svg>
        Назад
    </a>
    <h2>Предметы</h2>
    <a href="{% url 'subject_create' %}" class="btn btn-success mb-3">Добавить</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Название</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for subject in object_list %}
            <tr>
                <td>{{ subject.name }}</td>
                <td class="text-right">
                    <a href="{% url 'subject_update' subject.id %}" class="btn btn-primary">Редактировать</a>
                    <a href="{% url 'subject_delete' subject.id %}" class="btn btn-danger">Удалить</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}